#ifndef __UART_H_
#define __UART_H_
#ifdef __cplusplus
extern "C" {
#endif

#include "pid.h"

typedef struct __plan_TypeDef{
	
	stpvector_TypeDef pid;			//Plan generated by PID controller
	
	stpvector_TypeDef man;			//Plan generated manually

}plan_TypeDef;

int uart_Send(plan_TypeDef plan);

#ifdef __cplusplus
}
#endif
#endif // !__UART_H_